/*
Eduardo Kiyoshi Kamikabeya     9778536
Henrique Pasquini Santos         8532252
*/

--CRIACAO DAS TABELAS

-- Remocao das tabelas caso ja existam 
DROP TABLE ADAPTACAO CASCADE CONSTRAINTS;
DROP TABLE ATRACAOREG CASCADE CONSTRAINTS;
DROP TABLE CENTRO_DE_PRATICA CASCADE CONSTRAINTS;
DROP TABLE DELEGACAO CASCADE CONSTRAINTS;
DROP TABLE DELEGACAOMODALIDADE CASCADE CONSTRAINTS;
DROP TABLE EQUIPAMENTO CASCADE CONSTRAINTS;
DROP TABLE MODALIDADE CASCADE CONSTRAINTS;
DROP TABLE MODALIDADEMEMBRO CASCADE CONSTRAINTS;
DROP TABLE REGIAO CASCADE CONSTRAINTS;
DROP TABLE REGRAS CASCADE CONSTRAINTS;
DROP TABLE TRANSPORTE_EQUIP CASCADE CONSTRAINTS;
DROP TABLE TRANSPORTE_PESSOA CASCADE CONSTRAINTS;
DROP TABLE VEICULO CASCADE CONSTRAINTS;
DROP TABLE VEICULO_CARGA CASCADE CONSTRAINTS;
DROP TABLE VEICULO_PESSOAS CASCADE CONSTRAINTS;
DROP TABLE VEICULOMEMBRO CASCADE CONSTRAINTS;
DROP TABLE ATRACAO CASCADE CONSTRAINTS;
DROP TABLE ATRACAOREG CASCADE CONSTRAINTS;
DROP TABLE HOTEL CASCADE CONSTRAINTS;
DROP TABLE MEMBRO CASCADE CONSTRAINTS;

-- Tabela das 4 possiveis regioes do evento
CREATE TABLE REGIAO(
  NOME CHAR(10) CHECK( UPPER(NOME) IN ('COPACABANA', 'DEODORO', 'MARACANA', 'BARRA') ), -- Faz a comparacao corretamente independente da forma (caixa baixa ou alta) que é escrito
  PRIMARY KEY(NOME)
);

-- Tabela das atracoes turisticas da cidade
CREATE TABLE ATRACAO(
  NOME VARCHAR(20),
  ENDERECO VARCHAR(60),
  PRIMARY KEY(NOME)  
);

-- Tabela da relação NxN Regiao e Atracao Turistica
CREATE TABLE ATRACAOREG(
  REGIAO CHAR(10),
  ATRACAO VARCHAR(20),
  PRIMARY KEY(REGIAO, ATRACAO),
  FOREIGN KEY(REGIAO) REFERENCES REGIAO(NOME),
  FOREIGN KEY(ATRACAO) REFERENCES ATRACAO(NOME)
);

--Tabela dos hoteis da cidade
CREATE TABLE HOTEL(
  CNPJ CHAR(18),
  NOME VARCHAR(20),
  RUA VARCHAR(20),
  NUMERO NUMBER(4),
  PRIMARY KEY(CNPJ)
);

--Tabela das delegacoes que participam do evento
CREATE TABLE DELEGACAO(
  PAIS CHAR(10),
  HOTEL CHAR(18),
  PRIMARY KEY(PAIS),
  FOREIGN KEY(HOTEL) REFERENCES HOTEL(CNPJ) ON DELETE SET NULL --Caso um hotel for removido da tabela Hotel, os valores deste hotel nesta tabela se tornam nulos 
);

-- Tabela dos veiculos de transporte
CREATE TABLE VEICULO(
  PLACA CHAR(8),
  TIPO CHAR(10) CHECK (UPPER(TIPO) IN ('PESSOAS', 'CARGA')), --Somente essas 2 opcoes sao validas
  CPF_MOTORISTA CHAR(14),
  NOME_MOTORISTA VARCHAR(30),
  DELEGACAO CHAR(10),
  PRIMARY KEY(PLACA),
  UNIQUE(CPF_MOTORISTA),
  FOREIGN KEY(DELEGACAO) REFERENCES DELEGACAO(PAIS) ON DELETE SET NULL --Caso uma delegacao for removida da tabela Delegacao, os valores desta delegacao nesta tabela se tornam nulos 
);

-- Tabela dos veiculos que transportam pessoas
CREATE TABLE VEICULO_PESSOAS(
  PLACA CHAR(8),
  N_LUGARES NUMBER(2),
  PRIMARY KEY(PLACA),
  FOREIGN KEY(PLACA) REFERENCES VEICULO(PLACA) ON DELETE CASCADE --Caso um veiculo for removido da tabela Veiculo, as linhas que a contem serao removidas desta tabela
);

-- Tabela das adaptacoes dos veiculos
CREATE TABLE ADAPTACAO(
  PLACA CHAR(8),
  ADAPTACAO VARCHAR(20),
  PRIMARY KEY(PLACA, ADAPTACAO),
  FOREIGN KEY(PLACA) REFERENCES VEICULO_PESSOAS(PLACA) ON DELETE CASCADE --Caso um veiculo for removido da tabela Veiculo, as linhas que a contem serao removidas desta tabela
);

--Tabela dos veiculos que transportam carga
CREATE TABLE VEICULO_CARGA(
  PLACA CHAR(8),
  CAPACIDADE NUMBER(3),
  PRIMARY KEY(PLACA),
  FOREIGN KEY(PLACA) REFERENCES VEICULO(PLACA) ON DELETE CASCADE --Caso um veiculo for removido da tabela Veiculo, as linhas que a contem serao removidas desta tabela
);


-- Tabela dos membros participantes do evento
CREATE TABLE MEMBRO(
  N_CARTAO NUMBER(10),
  DELEGACAO CHAR(10) NOT NULL,
  PASSAPORTE CHAR(10),
  SEXO CHAR NOT NULL CHECK( UPPER(SEXO) = 'M' OR UPPER(SEXO) = 'F'),
  CPF CHAR(14),
  NOME VARCHAR(30) NOT NULL,
  COR_CARTAO CHAR(8) NOT NULL CHECK( UPPER(COR_CARTAO) IN ('AMARELO', 'AZUL', 'VERDE') ),  
  PRIMARY KEY(N_CARTAO),
  FOREIGN KEY(DELEGACAO) REFERENCES DELEGACAO(PAIS) ON DELETE CASCADE --Caso uma delegacao for removida da tabela Delegacao, as linhas que a contem serao removidas desta tabela
);

--Tabela da relacao NxN Veiculo e Membro
CREATE TABLE VEICULOMEMBRO (
  VEICULO CHAR(8),
  MEMBRO NUMBER(10),
  PRIMARY KEY (VEICULO, MEMBRO)
  );

-- Tabela dos equipamentos utilizados pelos atletas
CREATE TABLE EQUIPAMENTO(
  ID NUMBER(8),
  ATLETA NUMBER(10) NOT NULL,
  TIPO CHAR(25),
  QUANTIDADE NUMBER(2),
  VOLUME NUMBER(3),
  VEICULO CHAR(8),
  PRIMARY KEY(ID),
  FOREIGN KEY(ATLETA) REFERENCES MEMBRO(N_CARTAO) ON DELETE CASCADE,
  FOREIGN KEY(VEICULO) REFERENCES VEICULO(PLACA) ON DELETE SET NULL,
  UNIQUE(ATLETA, TIPO, QUANTIDADE) --chave secundaria
);

-- Tabela das modalidades de esporte
CREATE TABLE MODALIDADE(
  ID NUMBER(10),
  NOME VARCHAR(15) NOT NULL,
  CLASSE CHAR(10) NOT NULL,
  PRIMARY KEY(ID),
  UNIQUE(NOME, CLASSE) --chave secundaria
);

-- Tabela da relacao NxN Delegacao e Modalidade
CREATE TABLE DELEGACAOMODALIDADE(
  DELEGACAO CHAR(10),
  MODALIDADE NUMBER(10),
  PRIMARY KEY(DELEGACAO, MODALIDADE)
);
-- Tabela da relacao NxN Modalidade e Membro
CREATE TABLE MODALIDADEMEMBRO(  
  MODALIDADE NUMBER(10),
  MEMBRO NUMBER(10),
  PRIMARY KEY(MODALIDADE, MEMBRO)
);

-- Tabela das regras das modalidades
CREATE TABLE REGRAS(  
  MODALIDADE NUMBER(10),
  REGRA VARCHAR(150),
  PRIMARY KEY(MODALIDADE, REGRA)
);

--Tabela dos centros de pratica do evento
CREATE TABLE CENTRO_DE_PRATICA(  
  ID NUMBER(10),
  NOME VARCHAR(30),
  REGIAO CHAR(10),
  ENDERECO VARCHAR(40),
  PRIMARY KEY(ID),
  FOREIGN KEY(REGIAO) REFERENCES REGIAO(NOME) ON DELETE SET NULL,
  UNIQUE(NOME, REGIAO) -- chave secundaria
);

--Tabela dos transportes de pessoas realizados durante o evento
CREATE TABLE TRANSPORTE_PESSOA(
  CENTRO_DE_PRATICA NUMBER(10),
  VEICULO CHAR(8),
  MEMBRO NUMBER(10),
  DATA DATE,
  PRIMARY KEY(VEICULO, MEMBRO, DATA),
  FOREIGN KEY(CENTRO_DE_PRATICA) REFERENCES CENTRO_DE_PRATICA(ID) ON DELETE CASCADE,
  FOREIGN KEY(VEICULO) REFERENCES VEICULO(PLACA) ON DELETE CASCADE, 
  FOREIGN KEY(MEMBRO) REFERENCES MEMBRO(N_CARTAO) ON DELETE CASCADE
);

--Tabela dos transportes de equipamentos realizados durante o evento 
CREATE TABLE TRANSPORTE_EQUIP(
  CENTRO_DE_PRATICA NUMBER(10),
  VEICULO CHAR(8),
  EQUIPAMENTO NUMBER(8),
  DATA DATE,
  PRIMARY KEY(VEICULO, EQUIPAMENTO, DATA),
  FOREIGN KEY(CENTRO_DE_PRATICA) REFERENCES CENTRO_DE_PRATICA(ID) ON DELETE CASCADE, 
  FOREIGN KEY(VEICULO) REFERENCES VEICULO(PLACA) ON DELETE CASCADE,
  FOREIGN KEY(EQUIPAMENTO) REFERENCES EQUIPAMENTO(ID) ON DELETE CASCADE 
);
